# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1420f3cdc77133e401b9723105867bff4ae627b8224e24c8d1d7bec93ea4ed14e654961cf851463fa38564f25112094c53d1a9974d5331054d72f2a9ecb8e1

test:
  secret_key_base: b2033c38b4469705b075db31c13a34a4fffc37f0193122b8229f4a53da060de069acaacf9d5dec0ede39e31bf19294eba252ac68f62486c589c8fe2cbd73c729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
